### ISSUE TITLE
Not quite crash but fatal load exception, I'm not really sure

### ISSUE THREAD

**Issue by EXOgreen** [lyqyd/MyDrive#1]
I am making a new modpack with lots of CC and OC mods, but when I went to add yours here it wouldn't load up a old world or create a new one.

https://www.dropbox.com/s/33euaauzpsnr90w/MyDrive%20Error.log?dl=0

I can give you a copy of the pack and/or assist you in an way you need.

Added this mod and InPureCore at the same time, but when I disabled MyDrive it stopped.
also just tried it by turning on MyDrive and off inpure, still fatal exception has occurred.

**Comment by EXOgreen** [comment]
Another point, I turned off fastcraft, the error still occurred (some mod makers don't like crashes with fastcraft)

**Comment by EXOgreen** [comment]
Ok, so I didnt read through the crash log full last night and didnt have time to test, but today I found that in mods/MyDrive folder there was only a cache folder, no files folder. when I made that folder and put in a test program it loaded up the world. Have not tested with no program ihn the file, but im guessing it was just the not finding the file error.

**Comment by lyqyd** [comment]
Yep, the missing folder was likely the problem.  I'll work on pushing out a fix shortly!

**Comment by lyqyd** [comment]
I've pushed a release fixing this issue.  The new version ([v0.0.2](https://github.com/lyqyd/MyDrive/releases/tag/v0.0.2)) creates the folder automatically if it is not already present.

Thanks for the report!
